export const GET_DATA = 'GET_DATA';
export const GET_DATA_RECEIVED = 'GET_DATA_RECEIVED';
export const GET_DATA_STARTED = 'GET_DATA_STARTED';
export const GET_COBRANCA = 'GET_COBRANCA';
export const GET_COBRANCA_RECEIVED = 'GET_COBRANCA_RECEIVED';
export const GET_COBRANCA_STARTED = 'GET_COBRANCA_STARTED';
export const SET_COBRANCA = 'SET_COBRANCA';